dist: xenial
sudo: required
language: csharp
mono: none
dotnet: 2.2

globals:
  - DOTNET_SKIP_FIRST_TIME_EPErIENCE=true
  - DOTNET_CLI_TELEMETRY_OUTPUT=1

script:
  - dotnet restore
  - dotnet build -c Release OpenWeatherClient.sln
  - dotnet test -c Release OpenWeatherClient.sln